project_id = "qxaijnupaxxxsqaivbtj"

[functions.goae-chat]
verify_jwt = false

[functions.goae-credits]
verify_jwt = false

[functions.admin-context-upload]
verify_jwt = false

[functions.delete-account]
verify_jwt = true